[features]
seeds = false
[programs.localnet]
calor_vs_frio = "EGZx7ZRjewDocf8CFWwNkqSHDDDDMmw6VPZK4NifkhLs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/efren282/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
